pipeline:
  name: Inputset-practice
  identifier: Inputsetpractice
  projectIdentifier: VN
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: VikramTek
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Python
                    command: print("Hello, World!")
  variables:
    - name: image_tag
      type: String
      description: ""
      required: false
      value: <+input>
    - name: memory_limit
      type: String
      description: ""
      required: false
      value: <+input>.default(256Mi)
    - name: cpu_limit
      type: String
      description: ""
      required: false
      value: <+input>.default(250m)

